allowlist:
- {address: kms.us-east-2.amazonaws.com, port: 443}
- {address: kms-fips.us-east-2.amazonaws.com, port: 443}
- {address: kms.us-east-1.amazonaws.com, port: 443}
- {address: kms-fips.us-east-1.amazonaws.com, port: 443}
- {address: kms.us-west-1.amazonaws.com, port: 443}
- {address: kms-fips.us-west-1.amazonaws.com, port: 443}
- {address: kms.us-west-2.amazonaws.com, port: 443}
- {address: kms-fips.us-west-2.amazonaws.com, port: 443}
- {address: kms.af-south-1.amazonaws.com, port: 443}
- {address: kms-fips.af-south-1.amazonaws.com, port: 443}
- {address: kms.ap-east-1.amazonaws.com, port: 443}
- {address: kms-fips.ap-east-1.amazonaws.com, port: 443}
- {address: kms.ap-south-1.amazonaws.com, port: 443}
- {address: kms-fips.ap-south-1.amazonaws.com, port: 443}
- {address: kms.ap-northeast-3.amazonaws.com, port: 443}
- {address: kms-fips.ap-northeast-3.amazonaws.com, port: 443}
- {address: kms.ap-northeast-2.amazonaws.com, port: 443}
- {address: kms-fips.ap-northeast-2.amazonaws.com, port: 443}
- {address: kms.ap-northeast-1.amazonaws.com, port: 443}
- {address: kms-fips.ap-northeast-1.amazonaws.com, port: 443}
- {address: kms.ap-southeast-2.amazonaws.com, port: 443}
- {address: kms-fips.ap-southeast-2.amazonaws.com, port: 443}
- {address: kms.ap-southeast-1.amazonaws.com, port: 443}
- {address: kms-fips.ap-southeast-1.amazonaws.com, port: 443}
- {address: kms.ca-central-1.amazonaws.com, port: 443}
- {address: kms-fips.ca-central-1.amazonaws.com, port: 443}
- {address: kms.cn-north-1.amazonaws.com, port: 443}
- {address: kms-fips.cn-north-1.amazonaws.com, port: 443}
- {address: kms.cn-northwest-1.amazonaws.com, port: 443}
- {address: kms-fips.cn-northwest-1.amazonaws.com, port: 443}
- {address: kms.eu-central-1.amazonaws.com, port: 443}
- {address: kms-fips.eu-central-1.amazonaws.com, port: 443}
- {address: kms.eu-west-1.amazonaws.com, port: 443}
- {address: kms-fips.eu-west-1.amazonaws.com, port: 443}
- {address: kms.eu-west-2.amazonaws.com, port: 443}
- {address: kms-fips.eu-west-2.amazonaws.com, port: 443}
- {address: kms.eu-south-1.amazonaws.com, port: 443}
- {address: kms-fips.eu-south-1.amazonaws.com, port: 443}
- {address: kms.eu-west-3.amazonaws.com, port: 443}
- {address: kms-fips.eu-west-3.amazonaws.com, port: 443}
- {address: kms.eu-north-1.amazonaws.com, port: 443}
- {address: kms-fips.eu-north-1.amazonaws.com, port: 443}
- {address: kms.me-south-1.amazonaws.com, port: 443}
- {address: kms-fips.me-south-1.amazonaws.com, port: 443}
- {address: kms.sa-east-1.amazonaws.com, port: 443}
- {address: kms-fips.sa-east-1.amazonaws.com, port: 443}
- {address: kms.us-gov-east-1.amazonaws.com, port: 443}
- {address: kms-fips.us-gov-east-1.amazonaws.com, port: 443}
- {address: kms.us-gov-west-1.amazonaws.com, port: 443}
- {address: kms-fips.us-gov-west-1.amazonaws.com, port: 443}
