#!/bin/bash

# Install required packages
echo "===== Installing required packages ====="
sudo pip3 install -U pytest > /dev/null 2>&1

# Configure enclaves environment
echo "===== Configuring enclaves environment ====="

TESTS_MEM=2046

sudo sed -Ei "s/^memory_mib:.+\$/memory_mib: $TESTS_MEM/" /etc/nitro_enclaves/allocator.yaml
sudo systemctl restart nitro-enclaves-allocator.service

# Run integration tests
echo "===== Running integration tests except for the installation test ====="
python3 -m pytest /usr/share/nitro_enclaves/tests/integration/ --ignore /usr/share/nitro_enclaves/tests/integration/test_installation.py
