[package]
name = "rust-cose"
version = "0.1.0"
authors = ["Petre Eftime <epetre@amazon.com>"]
edition = "2018"

[dependencies]
serde_cbor = "0.10"
serde_repr = "0.1"
serde_bytes = "0.11"
serde_with = "1.3"
openssl = "0.10"

[dependencies.serde]
version = "1.0"
features = ["derive"]
