[package]
name = "aws-nitro-enclaves-eif-loader"
version = "1.0.0"
authors = ["The AWS Nitro Enclaves Team <aws-nitro-enclaves-devel@amazon.com>"]
edition = "2018"
rust-version = "1.94.1"
license = "Apache-2.0"
repository = "https://github.com/aws/aws-nitro-enclaves-cli"
description = "Loads an Enclave Image File (EIF) into a Nitro Enclave over vsock."

[lib]
name = "eif_loader"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[dependencies]
aws-nitro-enclaves-image-format = "0.8"
nix = "0.26"
libc = "0.2"
vsock = "0.5"

[dev-dependencies]
sha2 = "0.10"
tempfile = "3.19"

