/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
/*
 * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _UAPI_LINUX_NITRO_ENCLAVES_H_
#define _UAPI_LINUX_NITRO_ENCLAVES_H_

#include <linux/kvm.h>
#include <linux/types.h>

/* Nitro Enclaves (NE) Kernel Driver Interface */

/*
 * Note: The ioctl interface will be updated as additional logic is added
 * for the Nitro Enclaves PCI device and e.g. enclave image loading or CPU
 * handling.
 *
 * TODO: Update the ioctl interface once the necessary logic has been added.
 */

/**
 * The command is used to trigger enclave start after the enclave resources,
 * such as memory and CPU, have been set.
 *
 * The enclave start metadata is an in / out data structure. It includes
 * provided info by the caller - enclave cid and flags - and returns the
 * slot uid and the vsock loader token.
 */
#define NE_ENCLAVE_START _IOWR('B', 0x1, struct enclave_start_metadata)

/* Setup metadata necessary for enclave start. */
struct enclave_start_metadata {
	/**
	 * Context ID (CID) for the enclave vsock device.
	 * If 0, CID is autogenerated.
	 */
	__u64 enclave_cid;
	/* Flags for the enclave to start with (e.g. debug mode). */
	__u64 flags;
	/* Slot unique id mapped to the enclave to start. */
	__u64 slot_uid;
};

#endif /* _UAPI_LINUX_NITRO_ENCLAVES_H_ */
