name: Slack Pull Request notifications

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Notify owners via Slack
        run: |
          curl -d '{ "pr_url": "${{ github.event.pull_request.html_url }}" }' ${{ secrets.SLACK_WEBHOOK_URL }}
